//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoBiking.RoutingService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RoutingService.IRoutingService")]
    public interface IRoutingService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoutingService/getStationByCityName", ReplyAction="http://tempuri.org/IRoutingService/getStationByCityNameResponse")]
        string[] getStationByCityName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoutingService/getStationByCityName", ReplyAction="http://tempuri.org/IRoutingService/getStationByCityNameResponse")]
        System.Threading.Tasks.Task<string[]> getStationByCityNameAsync(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoutingService/getDirection", ReplyAction="http://tempuri.org/IRoutingService/getDirectionResponse")]
        string getDirection(string start, string destination, string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRoutingService/getDirection", ReplyAction="http://tempuri.org/IRoutingService/getDirectionResponse")]
        System.Threading.Tasks.Task<string> getDirectionAsync(string start, string destination, string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRoutingServiceChannel : GoBiking.RoutingService.IRoutingService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RoutingServiceClient : System.ServiceModel.ClientBase<GoBiking.RoutingService.IRoutingService>, GoBiking.RoutingService.IRoutingService {
        
        public RoutingServiceClient() {
        }
        
        public RoutingServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RoutingServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoutingServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RoutingServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string[] getStationByCityName(string name) {
            return base.Channel.getStationByCityName(name);
        }
        
        public System.Threading.Tasks.Task<string[]> getStationByCityNameAsync(string name) {
            return base.Channel.getStationByCityNameAsync(name);
        }
        
        public string getDirection(string start, string destination, string name) {
            return base.Channel.getDirection(start, destination, name);
        }
        
        public System.Threading.Tasks.Task<string> getDirectionAsync(string start, string destination, string name) {
            return base.Channel.getDirectionAsync(start, destination, name);
        }
    }
}
